name: Upload Python Package

on:
  workflow_dispatch:
  push:
    branches:
      - master
  release:
    types: [created]

permissions:
  contents: write
  id-token: write
  actions: write
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.X'  # Specify a specific Python version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-semantic-release setuptools-scm
    - name: Run semantic-release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        semantic-release version
        semantic-release publish 
